# Generated by Django 5.2.7 on 2025-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, help_text='Nama turnamen atau event', max_length=100, null=True)),
                ('site', models.CharField(blank=True, help_text='Lokasi pertandingan', max_length=100, null=True)),
                ('game_date', models.DateField(help_text='Tanggal permainan dimainkan')),
                ('round', models.CharField(blank=True, help_text='Babak ke berapa', max_length=10, null=True)),
                ('white_player', models.CharField(help_text='Nama pemain Putih', max_length=100)),
                ('black_player', models.CharField(help_text='Nama pemain Hitam', max_length=100)),
                ('white_elo', models.IntegerField(blank=True, help_text='Rating ELO pemain Putih', null=True)),
                ('black_elo', models.IntegerField(blank=True, help_text='Rating ELO pemain Hitam', null=True)),
                ('result', models.CharField(choices=[('1-0', 'White Wins'), ('0-1', 'Black Wins'), ('1/2-1/2', 'Draw'), ('*', 'Ongoing/Unknown')], help_text='Hasil akhir permainan', max_length=10)),
                ('pgn', models.TextField(help_text='Notasi permainan lengkap dalam format PGN')),
                ('eco_code', models.CharField(blank=True, help_text='Kode ECO pembukaan catur', max_length=10, null=True)),
                ('opening', models.CharField(blank=True, help_text='Nama pembukaan catur', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-game_date'],
            },
        ),
    ]
