# Generated by Django 5.2.7 on 2025-10-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='black_player',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='eco_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opening',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.TextField(help_text='Notasi permainan lengkap (PGN)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(blank=True, choices=[('1-0', 'Putih Menang'), ('0-1', 'Hitam Menang'), ('1/2-1/2', 'Remis'), ('*', 'Lainnya/Belum Selesai')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_player',
            field=models.CharField(max_length=100),
        ),
    ]
