# Generated by Django 5.2.7 on 2025-11-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0002_alter_game_black_elo_alter_game_black_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, help_text='Contoh: #Taktik, #Blunder', max_length=255, null=True),
        ),
    ]
