# Generated by Django 5.2.7 on 2025-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0003_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
