# Generated by Django 5.2.7 on 2025-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0004_alter_game_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
