# Generated by Django 5.2.7 on 2025-12-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0005_game_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama asli atau nama utama', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username di PGN (misal: DrNykterstein)', max_length=100)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='chess_db.playerprofile')),
            ],
        ),
    ]
