# Generated by Django 5.2.7 on 2026-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_db', '0006_playerprofile_playeralias'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white_player'], name='chess_db_ga_white_p_8b7a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player'], name='chess_db_ga_black_p_8dd103_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['event'], name='chess_db_ga_event_e04780_idx'),
        ),
    ]
